// This file is auto-generated by @hey-api/openapi-ts

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type GetApiHealthResponses = {
  /**
   * システムの稼働状況とISO形式のタイムスタンプを含むJSONオブジェクトを返却
   */
  200: {
    status: string;
    timestamp: string;
  };
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:3000' | (string & {});
};
